server:
  port: 9999

application:
  unidbg:
    dynarmic: false
    verbose: false
    async: false

spring:
  application:
    name: unidbg-boot-server
  profiles:
    active: dev
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        keep-alive: 60s
        max-size: 8
